project:
  type: website

website:
  title: "My Blog"
  navbar:
    right:
     
  
      - icon: folder-symlink
        href: https://www.youtube.com/@softdataconsult
      - icon: twitter
        href: https://twitter.com/seyiajao
      - icon: linkedin
        href: https://www.linkedin.com/in/isaac-oluwaseyi-ajao-datascientist-dataanalyst-statistician-consultant/
      - icon: envelope
        aria-label: email
        href: "mailto:mail.isaacoluwaseyiajao@gmail.com"  
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

